---
driver:
  name: docker
  binary: docker
  use_sudo: false

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu

suites:
  - name: create_webapp
    roles_path: roles
    run_list:
      - recipe[apt::default]
      - recipe[buildContainerTask::default]
    driver_config:
      privileged: true
      forward:
        - 80:80